### ISSUE TITLE
Stored GPS Coordinates in non-standard format

### ISSUE THREAD

**Issue by charisoudis** [RbnIzqGnl/PREVENTION-Toolkit#3]
Hello and thanks for publishing such an awesome dataset!

While trying to read the ego log (`logs/log_ego-vehicle.txt`), I noticed that GPS coordinates are in a NMEA-like format. However, without having the full message it would be difficult to decode those and transform them to e.g. decimal degrees. Do you have any transformation or link on how this could be done?

**Comment by RbnIzqGnl** [comment]
Dear achariso, thanks for using the PREVENTION dataset.

GPS coordinates are in NMEA format as lat/long (fields 3 and 4)  and in UTM format as nothing/easting (fields 5 and 6), which are metric coordinates.

**Comment by charisoudis** [comment]
Fields 5&6 did the job, thanks a lot!

**Comment by IvanGarcia7** [comment]
@RbnIzqGnl  In relation to the coordinates, Is it possible to associate the coordinates with each frame of the sequence?
