### ISSUE TITLE
Information about the speed

### ISSUE THREAD

**Issue by IvanGarcia7** [RbnIzqGnl/PREVENTION-Toolkit#5]
First of all, thank you for interesting dataset!

I'm trying to work with this dataset and I have some questions related to the speed of the vehicles. would it be possible to know the speed of the vehicle that has the LiDAR in each frame?.

The only label related to the speed that i have found is in the detections radarM.txt, which contains the longitudinal and lateral speeds in m/s.

**Comment by RbnIzqGnl** [comment]
Dear Ivan, thanks for using the PREVENTION dataset. 

If I have understood correctly, you want to know the speed of the ego-vehicle which is the vehicle that has the LiDAR installed.

The speed of the ego-vehicle can be found in the ego-vehicle log file "logs/log_ego_vehicle.txt" Field 13 (EKF_speed) has information related to the ego-vehicle speed and the timestamp (fields 1 and 2).

The camera log file "logs/log_camera1.txt" has the frame triggering time in the second column expressed as microseconds from the top of the day (from the midnight). This time framework is GPS-based so you can match it with the gpsChainTimeMS (second field in the ego-vehicle log). Note that the gpsChainTimeMS (second filed) is expressed in milliseconds not microseconds.

**Comment by IvanGarcia7** [comment]
@RbnIzqGnl Great!! thank you very much for your response. The last question I have regarding the annotations is in the trajectories.txt file. 

1. What are the parameters u and v. What are the parameters u and v? 
2. How are the variables x_cam y_cam z_cam x_laser y_laser z_laser expressed? In meters maybe?

Thank you in advance.
